### ISSUE TITLE
Unable to close window when using wslbridge2 with wsltty and WSL2

### ISSUE THREAD

**Issue by meatcar** [Biswa96/wslbridge2#10]
Pressing the close button on a terminal does nothing when running wsltty with wslbridge2 and wsl2.

**Steps to recreate:**

1. Install wslbridge2 to `%LOCALAPPDATA\wsltty\bin`. 
2. Run in `cmd`:
```
%LOCALAPPDATA%\wsltty\bin\mintty.exe  --configdir="%APPDATA%\wsltty" %LOCALAPPDATA%\wsltty\bin\hvpty.exe -W '$HOME' -l
```
3. Try to close the window with the X button on the top right. `^D` in the spawned shell works fine.

Confirmed with latest wsltty version `3.0.2.3` and wslbridge2 `v0.3`. 

Not sure if this is a wsltty bug or a wslbridge2 bug. I can cross-post if necessary.

**Comment by Biswa96** [comment]
I think it is by-design. The behavior is same with wslbridge2 and hvpty. @mintty any opinion.

**Comment by meatcar** [comment]
I'm running `hvpty.exe` in the example above. 

Do you mind clarifying the "by-design" aspect?

Looking through mintty source, I found that if you close the window while [holding <kbd>Shift</kbd>](https://github.com/mintty/mintty/blob/cdf94c3b4e37ce5b04933160fc1080f089288c49/src/winmain.c#L2186), mintty kills the child process with [`SIGKILL` instead of `SIGHUP`](https://github.com/mintty/mintty/blob/cdf94c3b4e37ce5b04933160fc1080f089288c49/src/child.c#L559). Thats good enough for me.

**Comment by mintty** [comment]
I've traced this in mintty and hvpty seems to resist the kill signal.

**Comment by Biswa96** [comment]
How do you trace things in mintty? Does it behave same with wslbridge2 (i.e. WSL1)? 

I have the test version of cygwin where both behaves same while pressing X (close) button.

**Comment by mintty** [comment]
I usually just add dedicated printf's and run mintty from another mintty.
It works with wslbridge2 for me. Same in cygwin 3.1.0.

**Comment by Biswa96** [comment]
@meatcar Can you check if the sample code in hvsocket folder behave same while pressing X (close) button in mintty?

I think cygwin does some book keeping for the AF_INET in wslbridge2 but hvpty uses raw AF_HYPERV socket from winsock.

**Comment by Biswa96** [comment]
Can anyone try to check if this attached patch fix this issue? [hvpty-test.patch.txt](https://github.com/Biswa96/wslbridge2/files/3685358/hvpty-test.patch.txt). Use `git apply`.

**Comment by meatcar** [comment]
@Biswa96 after a bunch of messing around with cygwin (never used it before), I finally have the patch built, and can confirm that it works :) Thanks!
