### ISSUE TITLE
execvp: No such file or directory (hvpty v0.4)

### ISSUE THREAD

**Issue by RShadowhand** [Biswa96/wslbridge2#14]
I've been trying to get hvpty to get to ~ (home directory of user) on launch, however no matter what tool I use (cmd, mintty-cyg, mintty-msys2) I get "execvp: No such file or directory". It works if I give an explicit path, but that's not an elegant solution.
It hasn't worked with previous versions either. I've been at this for 2-3 days now.

**Comment by Biswa96** [comment]
What command did you run?

**Comment by Biswa96** [comment]
What command did you run? The correct command will be this `hvpty.exe --wsldir "~"`. You can get more info with `hvpty.exe --help` command.

**Comment by RShadowhand** [comment]
I tried the following commands:
- `hvpty.exe` (started wsl where hvpty.exe was (i.e. C:\_Linux\bin))
- `hvpty.exe -` (execvp: No such file or directory)
- `hvpty.exe ~` (execvp: No such file or directory)
- `mintty.exe ./hvpty.exe` (Started hvpty where it was)
- `mintty.exe --WSL` (execvp: No such file or directory)

Let me try the one you suggested.

**Comment by RShadowhand** [comment]
Wow, that did work. I never thought to put double quotes around ~. You might want to clarify that in the readme. I had tried `-W ~`, but that ended up in the same thing.

**Comment by Biswa96** [comment]
OK, I will add the details in README. Thanks for using this.

**Comment by RShadowhand** [comment]
Thank you for the amazing tool.
