### ISSUE TITLE
Can't compile backend on Alpine anymore

### ISSUE THREAD

**Issue by mintty** [Biswa96/wslbridge2#17]
wslbridge2-backend.cpp:32:10: fatal error: linux/vm_sockets.h: No such file or directory
 #include <linux/vm_sockets.h>
          ^~~~~~~~~~~~~~~~~~~~

**Comment by Biswa96** [comment]
Required `linux-headers` package. Command: `sudo apk add linux-headers`.

**Comment by mintty** [comment]
Works after installing linux-headers. This was on a new installation, sorry.
