### ISSUE TITLE
X11 forwarding support

### ISSUE THREAD

**Issue by Uzume** [Biswa96/wslbridge2#19]
Perhaps I am misunderstanding something but it seems like `wslbridge2` is basically a WSL2 specific replacement for `ssh` (using a different/vm local socket type so it is inherently secure). As such, it would be really cool if this was extended so support X11 forwarding (and perhaps ssh agent forwarding other ssh types of port forwarding/tunneling too) so people can use this seamlessly with a Window X11 server (e.g., Cygwin/X, Xming, VcXsrv, X410, etc.).

I consider this an enhancement request since clearly nothing is really broken as _per se_.

**Comment by Uzume** [comment]
This would allow for one to run X11 apps in WSL without having to configure a local Windows X11 server for remote access, entirely getting around issues like microsoft/WSL#4106.

**Comment by Biswa96** [comment]
The goal of wslbridge is to bridge WSL and Windows world. It does not do any processing with the data and does not know what data is being passed. So, the responsibility is upon the end programs (in this case, it is X server e.g. Xserver, Xming, X410) to process the data. 

See the [FAQ][1]. If you execute `wslbridge2.exe -e WSL_HOST_IP` command then pass the variable to display like this `export DISPLAY=$WSL_HOST_IP:0` you do not have to configure any other settings.

[1]: https://github.com/Biswa96/wslbridge2/blob/master/FAQ.md

**Comment by Biswa96** [comment]
Any reply?

**Comment by Uzume** [comment]
That still requires the use of another IP address without any sort of tunneling (which opens X server security issues and the IP can and does change from boot to boot). I am more interested in a way to avoid that and keep DISPLAY on localhost (but just a different tunneled/forwarded port). I am not suggesting it needs to be an X specific type of thing but some sort of tunneling would be good. Then the "data" in the tunnel can still be arbitrary and wslbridge need not know what it is specifically but an X11 forwarding or other type of tunneled data could still be created at an application level.

**Comment by sarim** [comment]
I see @Biswa96 added a flag for `Enables X11 forwarding`. What does this flag do?

**Comment by Biswa96** [comment]
I have added that as a dummy flag, see the commit message. I am working on it but there are synchronization problem. I hope to figure it out quickly.

**Comment by Biswa96** [comment]
BTW, the main problem is to use ReadFile/WriteFile asynchronously with two sockets in full duplex mode but in one channel.

**Comment by Biswa96** [comment]
I have added that as a dummy flag, see the commit message. I am working on it but there are synchronization problem. I hope to figure it out quickly. The main problem is to use ReadFile/WriteFile asynchronously with two sockets in full duplex mode but in one channel in C without using any library.

**Comment by sarim** [comment]
I see, TBH I don't really need the functionality. I've been using X11 from the beginning of WSL2 with `DISPLAY=WINDOWS_IP:0` without any problem. I'm not concerned with security issue either as everything is behind windows firewall. I was just curious after seeing the flag :3

**Comment by Biswa96** [comment]
> I've been using X11 from the beginning of WSL2 with `DISPLAY=WINDOWS_IP:0` without any problem.

I have also suggested that in my first comment. But one need to add a firewall rule to allow X server in Windows. That may not be permitable in constrained environment. Also @Uzume comment gave me a spark.

> Then the "data" in the tunnel can still be arbitrary and wslbridge need not know what it is

The channel can be extended to anything e.g. pulseaudio, our own localhost fowarding, WTF we want, no Microsoft's blessings.

**Comment by sarim** [comment]
> The channel can be extended to anything e.g. pulseaudio, our own localhost fowarding, WTF we want, no Microsoft's blessings.

That is indeed very interesting. I guess it'd also solve many prople's problems in https://github.com/microsoft/WSL/issues/4150 . Where people are using netsh portproxy to forward tcp ports, and portproxy doesn't support udp.

**Comment by Biswa96** [comment]
Microsoft's WSL devs are not just chilling. There is some network thingy going on. Maybe they will reveal that for next 'Microsoft Build 2021/22' event. For example, LxssManager.dll got this in `.wslconfig` file:

```ini
[wsl2]
mirroredNetworking=true
```

**Comment by Biswa96** [comment]
🔥 **IMPORTANT:** I have done some testing with this. But there will be a practical limitation which slows down connection. The X11 buffer has to pass through so many layers like this:

```
x11 app <--> localhost <--> backend <--> vsock <--> frontend <--> localhost <--> x11 server
```

This makes the X11 app much slower than normal localhost connection. Suggestions are welcomed.

**Comment by sarim** [comment]
How slow? fps numbers from a benchmark tool? maybe glxgears?

Also how do can I check it? Did you push the commit?

Doesn't hyperv use the same vsock for xrdp? It seems to run good enough.

**Comment by Biswa96** [comment]
To be done...

**Comment by Biswa96** [comment]
To be done...

**Comment by Biswa96** [comment]
Now there is WSLg feature available. This is not required anymore... ✌️
