### ISSUE TITLE
Windows 10 1803 (build 17134) Support

### ISSUE THREAD

**Issue by xlongshu** [Biswa96/wslbridge2#20]
[wslbridge2.cpp](https://github.com/Biswa96/wslbridge2/blob/master/src/wslbridge2.cpp#L169)
`if (GetWindowsBuild() < 17134)`
![image](https://user-images.githubusercontent.com/18544924/75340801-20802e00-58ce-11ea-9136-bf32df8a4793.png)

**Comment by Biswa96** [comment]
For older Windows 10 versions, use [wslbridge](https://github.com/rprichard/wslbridge.git) program.

**Comment by Biswa96** [comment]
For older Windows 10 versions, use [wslbridge](https://github.com/rprichard/wslbridge.git) program. This wslbridge2 is based upon that wslbridge repository.

**Comment by Biswa96** [comment]
Did you use wslbridge project?

**Comment by Biswa96** [comment]
According to the [Windows 10 Release Information][1], Windows 10 version 1803 (build 17134) is end of service now. Closing this issue. Please use newer Windows 10 version 🙏 

[1]: https://docs.microsoft.com/en-us/windows/release-information/
