### ISSUE TITLE
wslbridge2 waits for setsid program to finish

### ISSUE THREAD

**Issue by Perlence** [Biswa96/wslbridge2#23]
Hello,

I started wslbridge2 v0.5 from a regular command prompt window:

```bat
C:\cygwin\bin>wslbridge2
```

Next, I did the following:

```bash
$ setsid sleep 10
$ exit
```

I expected the wslbridge2 process to exit immediately. However, it waits for `sleep` to finish before exiting.

First, I thought that it was a mintty issue https://github.com/mintty/mintty/issues/993, but it also happens in Command Prompt.

**Comment by Biswa96** [comment]
Any probable reason or solution for this issue? I am out of ideas. Try to open a CMD window with wsl.exe and open htop in it. See the process tree.

**Comment by Biswa96** [comment]
I have changed something to fix this issue. Would you like to try the artifacts from the Appveyor build? See this green tick above.

**Comment by Biswa96** [comment]
I have changed something to fix this issue. Would you like to try the artifacts from the Appveyor build? See this green tick above. /cc @mintty

**Comment by mintty** [comment]
Seems to fix this issue. But: it failed to run Ubuntu for me (backend compiled with Alpine).

**Comment by Biswa96** [comment]
Did you do the static linking? I am currently running/testing 5 distros both in WSL1 and WSL2 without any issue.

**Comment by mintty** [comment]
Oh, right. It works.

**Comment by Perlence** [comment]
@Biswa96 Great work! Thank you very much!

**Comment by mintty** [comment]
Can you make it a release, please?

**Comment by Biswa96** [comment]
Done. v0.6 is re-tagged.
