### ISSUE TITLE
Re-license Get-VmID.{cpp,hpp} using LGPL 2.1+?

### ISSUE THREAD

**Issue by e45lee** [Biswa96/wslbridge2#26]
Hi,

I've got a set of patches against PulseAudio (https://github.com/e45lee/pulseaudio-hyperv/) for running a PulseAudio server instance on Windows listening on Hyper-V sockets.  These changes use your VM ID detection code for determining the appropriate VM to bind to, as binding to the wildcard address doesn't allow the WSL2 VM to connect to the socket.

I'm thinking of making a PR for these changes upstream, and ideally I'd like to upstream these changes with PulseAudio's existing licensing (which is LGPL 2.1 or later).  I think I can contribute a patch that is GPL 3 though, but...

1. Is the current license on Get-VmID.cpp an oversight?  All the other files in the repository are GPL 3 or later, but this one in particular is GPL 3 _only_.  https://github.com/Biswa96/wslbridge2/blob/a8e3481a6ef1b046ac7f13a41161b493d1c99583/src/GetVmId.cpp#L3 (compared to) https://github.com/Biswa96/wslbridge2/blob/a8e3481a6ef1b046ac7f13a41161b493d1c99583/src/GetVmId.hpp#L3
2.  Is it possible to re-license Get-VmID.{hpp,cpp} to LGPL 2.1+?

**Comment by Biswa96** [comment]
> Is the current license on Get-VmID.cpp an oversight? 

Typo. I will add the rest.

> Is it possible to re-license Get-VmID.{hpp,cpp} to LGPL 2.1+?

Nope. Never.

>  These changes use your VM ID detection code for determining the appropriate VM

The code in wslbridge2 uses undocumented COM interface to get the VM ID. DO NOT use the logic in any important project, like pulseaudio here. The undocumented WSL2 logic may change in future. If you want to get WSL2 VM ID then you can follow Docker's code (golang) which uses Hyper-V APIs.

**Comment by e45lee** [comment]
> 
> 
> > Is the current license on Get-VmID.cpp an oversight?
> 
> Typo. I will add the rest.

Cool, thanks for the clarification.

> 
> > Is it possible to re-license Get-VmID.{hpp,cpp} to LGPL 2.1+?
> 
> Nope. Never.
> 
> > These changes use your VM ID detection code for determining the appropriate VM
> 
> The code in wslbridge2 uses undocumented COM interface to get the VM ID. DO NOT use the logic in any important project, like pulseaudio here. The undocumented WSL2 logic may change in future. If you want to get WSL2 VM ID then you can follow Docker's code (golang) which uses Hyper-V APIs.

Yeah, I was debating the merits of this, as usually undocumented APIs tend to be stable in Windows.  I glanced at what Docker does, but I don't think I'll use that approach as it requires elevated privileges.  What I'll probably do is I'll make a PR in PulseAudio for Hyper-V sockets without VM detection, and leave it up to the user to fill in the appropriate GUID (HV_SOCKET_WILDCARD or specific VM ID) to bind to as a configuration option.

**Comment by Biswa96** [comment]
Have you send any PR in upstream with your idea? Curious about it 🤤

**Comment by e45lee** [comment]
Not yet, I've been busy unfortunately.  I was thinking of doing something more general for PulseAudio -- to implement VM sockets on Linux and Windows -- but I haven't had the time for that.
