### ISSUE TITLE
feature request: a flag to see version of wslbridge and expose version to a ENV var in linux

### ISSUE THREAD

**Issue by sarim** [Biswa96/wslbridge2#29]

**Comment by Biswa96** [comment]
It is really necessary 🤔 There is no breaking changes between versions. I am reserving `-v` option for verbose mode or something else.

**Comment by sarim** [comment]
In a perfect world It wouldn't be necessary but right now I'm switching between 3 terminals - Windows Terminal, wsltty/mintty, conemu (wslbridge2). I'm changing versions when encountering bugs. I thought it'll be useful to know which version of wslbridge I'm running.

After thinking some more, maybe you don't need to use a flag if you don't want to. Maybe add the version in `-h` output?

**Comment by Biswa96** [comment]
> Maybe add the version in -h output?

OK, perfect choice.

**Comment by Biswa96** [comment]
I have added the version number in help command output. Would you like to check it please?

**Comment by sarim** [comment]
Yes, it is working. (y) I'm just nitpicking at this point, but is manually defining version necessary? I think  WSLBRIDGE2_VERSION can be defined from Makefile when compiling, and Makefile will get it by running `git describe --long HEAD --tags`

**Comment by Biswa96** [comment]
Just a choice. That command will not work in shallow clone repository, which I do frequently. Also one does not have to install git to build this program from released tarball. 🤟

**Comment by Biswa96** [comment]
I have re-tagged this change to v0.7 release.
