### ISSUE TITLE
Implementing Interop

### ISSUE THREAD

**Issue by djhohnstein** [Biswa96/wslbridge2#33]
This isn't an issue - this is me not understanding how WSL works and seeking clarity.

I've been trying to grok the work between here, lxss, mintty, and some of your other projects involving WSL and WSL2. Essentially, my aim is to launch a process in WSL/WSL2 from Windows (such as, "/usr/bin/whoami") and retrieve the output. My questions are two-fold:

1. How did you derive these function definitions and names? I was perusing the COM objects using the OLE.NET viewer from James Foreshaw, but didn't see the symbols you retrieved (or how you derived the function parameters for that matter). 
2. How could I achieve my goal (such as running /usr/bin/whoami) from Windows using this interop? For context, I'm running on Windows 11 using Ubuntu distribution, but I believe your typedefs are correct as copying the code from this project as-is seems to work for CreateLxProcess when passing nullptr to several variables (as done here: https://github.com/Biswa96/wslbridge2/blob/master/src/GetVmId.cpp#L218-L233), but when I attempt to populate them I receive an invalid memory read. Sample code and error is attached:

![image](https://user-images.githubusercontent.com/9327224/168207332-d01d0038-110f-46e4-bf8d-4efb06b94ff0.png)

```C++
HRESULT hRes;
    GUID InitiatedDistroID;
    HANDLE LxProcessHandle, ServerHandle;
    SOCKET SockIn, SockOut, SockErr, ServerSocket;
    SockIn = win_vsock_create();
    SockOut = win_vsock_create();
    SockErr = win_vsock_create();
    ServerSocket = win_vsock_create();

    // Initialize StdHandles members to be console handles by default.
    // otherwise LxssManager will catch undefined values.
    LXSS_STD_HANDLES StdHandles;
    memset(&StdHandles, 0, sizeof StdHandles);
    
    // Provides \Device\ConDrv\Connect interface of attached ConHost.
    const HANDLE ConsoleHandle = NtCurrentTeb()->
                                 ProcessEnvironmentBlock->
                                 ProcessParameters->
                                 Reserved2[0];

    const int WindowsBuild = GetWindowsBuild();
    std::string bin("/usr/bin/bash");
    std::string args("-c whoami");
    LPCSTR lpcArgv = args.c_str();
    /* Before Build 20211 Fe */
    if (WindowsBuild < 20211)
    {
       // snipped
    }
    else
    {
        /* After Build 20211 Fe */
        PCWSTR LxssDefaultEnvironmentStrings[4] =
        {
            L"HOSTTYPE=x86_64",
            L"TERM=xterm",
            L"LANG=en_US.UTF-8",
            L"SHELL=/usr/bin/bash"
        };
        hRes = ComObj.wslSessionThree->lpVtbl->CreateLxProcess(
            ComObj.wslSessionThree,
            DistroId,
            bin.c_str(),
            3,
            &lpcArgv,
            L"C:\\Windows\\System32;C:\\Windows",
            L"/",
            *LxssDefaultEnvironmentStrings,
            4,
            L"user",
            0,
            0,
            HandleToULong(ConsoleHandle),
            &StdHandles,
            0, // maybe update this to 1?
            &InitiatedDistroID,
            LxInstanceID,
            &LxProcessHandle,
            &ServerHandle,
            &SockIn,
            &SockOut,
            &SockErr,
            &ServerSocket);
    }

    assert(hRes == 0);

    /* wsltty#254: Closes extra shell process. */
    if (SockIn) closesocket(SockIn);
    if (SockOut) closesocket(SockOut);
    if (SockErr) closesocket(SockErr);
    if (LxProcessHandle) CloseHandle(LxProcessHandle);
    if (ServerHandle) CloseHandle(ServerHandle);

    if (ComObj.wslSessionOne)
        ComObj.wslSessionOne->lpVtbl->Release(ComObj.wslSessionOne);
    CoUninitialize();
    return hRes;
```

Any insight you could give me or pointers to put me in the right direction would be helpful. Thanks for your time!

**Comment by Biswa96** [comment]
> my aim is to launch a process in WSL/WSL2 from Windows (such as, "/usr/bin/whoami") and retrieve the output

Then you should use the official way. Run `wsl.exe whoami` or `wsl.exe --exec whoami` using [CreateProcess][1]. Then get the output using a pipe in StartupInfo.hStdOutput field.

[1]: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa

**Comment by djhohnstein** [comment]
Thanks for your response! While I could launch a child process, I'd much rather leverage COM in my application. Could you point me to the resources you used to generate your stub definitions for things like ILxssUserSession? If not I'll continue going down the rabbit hole of reversing bash.exe/wsl.exe.

**Comment by Biswa96** [comment]
⚠️ Warning: The COM interfaces are undocumented and varies according to Windows versions.

> How did you derive these function definitions and names?

I get those from LxssManager.dll.

> How could I achieve my goal (such as running /usr/bin/whoami) from Windows using this interop?

If you want to interop from CreateLxProcess that would be a huge job. First you have to read/write console buffers with SockIn, SockOut and SockErr sockets. Then read/write the message buffers from ServerSocket which uses it's own buffer and message types.

> but when I attempt to populate them I receive an invalid memory read

I have not test your code as is. From a quick glance, there may be some issues in the variables initialization. e.g. the arguments are array of strings, environments and current directory should be in Windows style etc.

> Could you point me to the resources you used to generate your stub definitions for things like ILxssUserSession?

Everything is undocumented as expected 😄 The ILxssUserSession interface is implemented in LxssManager.dll.

**Comment by djhohnstein** [comment]
Could you explain more how SockIn/SockOut/SockErr/ServerSocket works? It seems like SockIn/Out/Err is used for process IO, but I'm not quite sure how ServerSocket plays into it.

Far as the example code goes, I was able to compile this project by reinstalling cygwin with the appropriate dependencies so I think I have enough to start playing around and (hopefully) get things working.

Thanks again for taking the time to explain things to a novice like myself! There's a lot of moving components that I'm still wrapping my head around.

**Comment by Biswa96** [comment]
SockIn/SockOut/SockErr are normal read/write sockets like stdin/stdout/stderr. But those are valid for WSL2 only. For WSL1, it is required to do some ioctl exchanges with lxss.sys driver. The ServerSocket is a huge topic. The messages depends on WSL1 or WSL2. Those also changes with each Windows versions.
For simple interop, you can use own managed sockets and pty to receive/send buffers like wslbridge or wslbridge2 does.

**Comment by djhohnstein** [comment]
Is there a way to launch a subsystem process (like `whoami`) without launching wsl.exe under the hood? I'm still tinkering with things and have communication over the sockets, but didn't know if I could simply launch the PICO process directly and start communicating with it via the established sockets

**Comment by Biswa96** [comment]
> Is there a way to launch a subsystem process (like whoami) without launching wsl.exe under the hood?

The COM interfaces do not launch wsl.exe.

**Comment by djhohnstein** [comment]
Ah! I've cracked it thanks to some of your other projects. Appreciate your patience with me. Amazing work and look forward to following your next project!

**Comment by Biswa96** [comment]
This repository is being used by many users so I keep unstable bits as low as possible. But if you want to play with internal stuff this repository is my playground https://github.com/Biswa96/WslReverse. If you require anything I can try to add it there (assuming I have sufficient time). I am using Windows 10. Hence some parts in that repository might not work in Windows 11.

**Comment by goyalyashpal** [comment]
> Ah! I've cracked it thanks to some of your other projects.

@djhohnstein what was it?? any wisdom worth sharing back here??

**Comment by yashpalgoyal1304** [comment]
@djhohnstein
