### ISSUE TITLE
could wslbridge2 be made a cygwin package

### ISSUE THREAD

**Issue by goyalyashpal** [Biswa96/wslbridge2#34]
### Summary

If `wslbridge2` could be made a cygwin package, then `mintty` could somehow be directly used as `wsltty` - thus, for msys2 users, reducing duplicacy of installed softwares and also confusion among users

### Details

Refer to https://github.com/mintty/mintty/issues/1166#issuecomment-1179566419 for details, TL;DR:
* mintty is already included in msys2/cygwin
* for using it with wsl, either wsltty has to be installed separately, or wslbridge has to be installed at /bin

**Comment by Biswa96** [comment]
I am not familiar with cygwin packaging. Feel free to package it for cygwin.

In case of msys2, the wslbridge2 package is unnecessary. "the main focus of MSYS2 is to provide a build environment for native Windows software and the Cygwin-using parts are kept at a minimum"[^1]

[^1]: https://www.msys2.org/

**Comment by goyalyashpal** [comment]
i am well aware of that, i meant the following use case:
* a user has already MSYS2 installed, and
* per likes msys2's mintty, and
* per installs wsl2 as well
* so, now per has to install wsltty additionally, so, there would be
redundancy of this application, two different setups, themes,
customisations, etc.
* if wslbridge2 package is available in msys2, then per can use the
existing msys2's mintty as wsltty as well

Biswapriyo Nath wrote:

**Comment by Biswa96** [comment]
Agree. I can provide a package for msys2 only. I am not familiar with cygwin packaging _yet_. But I can try.

**Comment by Biswa96** [comment]
I have added a msys2 package just for testing. I need to learn the cygwin packaging.

BTW, there would be some issues with cygwin/msys2 packages. For example, if the drvfs (e.g. /mnt/c/) mount options does not have execute bit set or disabled then the wslbridge2-backend will not be executed. It is done by wsltty installer.

**Comment by goyalyashpal** [comment]
hey, so, how to proceed? what steps to take next?? i am thinking of following ( based on https://github.com/mintty/mintty/issues/1166#issuecomment-1179566419 )

1. check and fix that drvfs mount option - how?

2. install that package - how?
the above src says: > _"install wslbridge2 in your /bin"_

3. running mintty with wslbridge - `mintty --WSL`

----
as for step 2:

I couldn't find the package, have tried all the different commands i could think of: 

```bash
pacman -Syi wslbridge
pacman -Syi wslbridge2
pacman -Qu wslbridge
pacman -Qu wslbridge2
```

it always showed same thing: `error: package 'wslbridge2' was not found` (or wslbridge depending on what i input

**Comment by Biswa96** [comment]
> check and fix that drvfs mount option - how?

From user perspective, if you didn't add any mount options in /etc/wsl.conf file it's good to go. From developer perspective, the wslbridge2.exe has to check or add NTFS extended attributes. Or run `wsl.exe chmod +x` as mintty installer does. Though I'm trying to focus on stabilizing the normal use cases.

> install that package - how?

I've only added the msys2 package in release page of this project. It can not be added in msys2 Pacman repository because msys2 focuses on native mingw packages. Also the backend is an ELF file, so not fully buildable in cygwin/msys2. I've manually built it in my machine.

To install it in msys2, download the .pkg.tar file and install it with `pacman -U <file path>` command.

**Comment by goyalyashpal** [comment]
awesome. i just did the given installing command `pacman -U <file(s)>` without checking anything else (the drvfs mount options or anything else) and it worked.

`mintty --WSL` (yes, in caps)

i think this issue can be closed from my side then... feel free to reopen

'cz i dont use cygwin 😅 _yet_ 😆 
_and the title?_ i just followed the lead from the other linked issue

----
**Self ntoes:**
* `mintty --wsl` is wrong, but doesnt give any expected "error" - it's pro'lly right in not giving any error, but causes trouble on human side lol
* `pacman -Rs wslbridge2` for removing/uninstalling the package (via wiki.arch/[Pacman])

[Pacman]: https://wiki.archlinux.org/title/Pacman#Removing_packages

**Comment by Biswa96** [comment]
Thanks for this little nudge. I have figured out to build whole wslbridge2 project in CI. The Linux part will be built in Alpine Docker image. Just need some polishing.

**Comment by goyalyashpal** [comment]
umh, what does it mean for me? 😅

**Comment by Biswa96** [comment]
For you, you can get compiled binaries from CI artifacts. For me, I can find any regression easier than before.
