### ISSUE TITLE
assertion "hRes == 0" failed: file "GetVmId.cpp", line 181, function: HRESULT GetVmId(GUID*, GUID*)

### ISSUE THREAD

**Issue by nufeng1999** [Biswa96/wslbridge2#35]
assertion "hRes == 0" failed: file "GetVmId.cpp", line 181, function: HRESULT GetVmId(GUID*, GUID*)

**Comment by Biswa96** [comment]
For quick fix, download the CI artifact from here https://ci.appveyor.com/project/Biswa96/wslbridge2/build/job/q3y0vyk50s27up5b/artifacts. Extract it in existing wslbridge2 directory. I am going to release a tag now.

⭐ One caveat. If you are using WSL Preview from Store run wsl.exe first, close it, then wslbridge2.exe. It is a execution permission issue which _will_ be solved with https://github.com/mintty/wsltty.appx. Not ready yet.

**Comment by Biswa96** [comment]
For quick fix, download the CI artifact from here https://ci.appveyor.com/project/Biswa96/wslbridge2/build/job/q3y0vyk50s27up5b/artifacts. Extract it in existing wslbridge2 directory.

⭐ One caveat. If you are using WSL Preview from Store run wsl.exe first, close it, then wslbridge2.exe. It is a execution permission issue which _will_ be solved with https://github.com/mintty/wsltty.appx. Not ready yet.

**Comment by halsn** [comment]
> For quick fix, download the CI artifact from here https://ci.appveyor.com/project/Biswa96/wslbridge2/build/job/q3y0vyk50s27up5b/artifacts. Extract it in existing wslbridge2 directory.
> 
> ⭐ One caveat. If you are using WSL Preview from Store run wsl.exe first, close it, then wslbridge2.exe. It is a execution permission issue which _will_ be solved with https://github.com/mintty/wsltty.appx. Not ready yet.

The url you provided said 'The build job does not contain any artifacts', how can I get the CI artifact?

**Comment by Biswa96** [comment]
Here is the new build https://ci.appveyor.com/project/Biswa96/wslbridge2/builds/44602285/job/ijt8cc3ft1pdq64s/artifacts. I shall try to provide a tagged release ASAP.

**Comment by halsn** [comment]
> Here is the new build https://ci.appveyor.com/project/Biswa96/wslbridge2/builds/44602285/job/ijt8cc3ft1pdq64s/artifacts. I shall try to provide a tagged release ASAP.

Thanks a lot, it works!

**Comment by Biswa96** [comment]
I have added the workaround in [v0.9](https://github.com/Biswa96/wslbridge2/releases/tag/v0.9) release. The program can be downloaded from there.

The issue has not been fixed yet. I have a fix for that but it requires the current user to be a member of Hyper-V Administrator group. But it requires this command to be run as admin `net localgroup "Hyper-V Administrators" %user% /add` once.

**Comment by Biswa96** [comment]
Please try the CI artifacts from here https://ci.appveyor.com/project/Biswa96/wslbridge2/builds/45244286/job/dtg7beug6j48fyst/artifacts. Extract both files from that zip file in existing installation. It should work with both WSL Preview and system WSL without any workaround.

**Comment by Biswa96** [comment]
This issue has been fixed in [version 0.10](https://github.com/Biswa96/wslbridge2/releases/tag/v0.10). Please test the binaries. If the problem persists feel free to reopen this issue. Thank you ❤️
