### ISSUE TITLE
ERROR: GetVmId:271: CreateLxProcess: the system cannot find the file specified

### ISSUE THREAD

**Issue by rola25** [Biswa96/wslbridge2#38]
When I try to start wslbridge2 with a WSL2 Distriburtion (e.g. wslbridge2.exe -d centos7) I get this error. If I start the distribution with "wsl -d centos7" it works, and after that, when I try to start "wslbridge2.exe -d centos7) it also works. When I do "wsl --shutdown" the same error reappears. Any ideas why?

Thanks
br
rola

**Comment by Biswa96** [comment]
Do you have wslbridge2-backend in the same directory of wslbridge2.exe?

**Comment by Biswa96** [comment]
Can you provide some more details? Like Windows version, is it WSL from store, how did you install centos etc.

**Comment by rola25** [comment]
Hi

Windows Version:
![image](https://user-images.githubusercontent.com/40626700/209940528-1d096da6-7608-4f15-ae7f-764dde76a84e.png)

WSL:
wsl --version
WSL-Version: 1.0.3.0
Kernelversion: 5.15.79.1
WSLg-Version: 1.0.47
MSRDC-Version: 1.2.3575
Direct3D-Version: 1.606.4
DXCore-Version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows Version: 10.0.19045.2311

I installed Centos7 with wsldl: https://github.com/yuk7/wsldl
But it affects all version 2 WSL Distros which I have installed.

When I open ANY v2 WSL distro with wsl -d <any distro> in advance, then wslbridge2.exe works. But after "wsl --shutdown" I have the same problem again.

wslbridge2-backend is in the same dir:

 Verzeichnis von C:\Users\xxxxx\AppData\Local\wsltty\bin

28.12.2022  12:32    <DIR>          .
28.12.2022  12:32    <DIR>          ..
08.11.2022  23:04            42 515 cygwin-console-helper.exe
01.01.1601  01:07         3 588 124 cygwin1.dll
01.01.1601  01:07         3 588 124 cygwin1.dll.1
08.11.2022  23:04           108 544 dash.exe
08.11.2022  23:04           973 312 mintty.exe
08.11.2022  23:04            25 619 regtool.exe
01.01.1601  01:07           207 232 wslbridge2-backend
01.01.1601  01:07           207 232 wslbridge2-backend.1
01.01.1601  01:07           188 928 wslbridge2.exe
01.01.1601  01:07           188 928 wslbridge2.exe.1
28.12.2022  12:32         1 426 483 wslbridge2_cygwin_x86_64.zip
08.11.2022  23:04            89 600 zoo.exe

How do I know if it is the store-Version of WSL?

Thanks
br
rola

**Comment by Biswa96** [comment]
> How do I know if it is the store-Version of WSL?

It's simple, `wsl --version` always works if store version of WSL is installed :)

> I installed Centos7 with wsldl

I am not familiar with that tool. Can you provide the procedure how to install centos7 with that tool?

**Comment by Biswa96** [comment]
It's working in my system though

![image](https://user-images.githubusercontent.com/31443074/209953145-1e589ce8-bb1e-453d-881e-66893abb1648.png)

Have you tried the latest wsltty installer version 3.6.1.2 ? Link https://github.com/mintty/wsltty/releases

**Comment by rola25** [comment]
Yes I have tried. Here is my result (my default wsl distro is v1, this works everytime) (Das System kann die angegebene Datei nicht finden= German = The system cannot find the file specified):

PS C:\Users\xxxx\AppData\Local\wsltty\bin> .\wslbridge2.exe
root@RP-T14:/mnt/c/Users/xxxx/AppData/Local/wsltty/bin# exit
PS C:\Users\xxxx\AppData\Local\wsltty\bin> .\wslbridge2.exe -d centos7
ERROR: GetVmId:271: CreateLxProcess: Das System kann die angegebene Datei nicht finden.

PS C:\Users\xxxx\AppData\Local\wsltty\bin>

**Comment by Biswa96** [comment]
I am unable to find any possible cause. Can you provide the procedure how to install centos7 with that tool? Does `wsl.exe -d centos7` work?

**Comment by rola25** [comment]
Yes wsl -d centos7 works:
Here the procedure:

```
PS C:\Users\xxxx\AppData\Local\wsltty\bin> .\wslbridge2.exe -d centos7
ERROR: GetVmId:271: CreateLxProcess: Das System kann die angegebene Datei nicht finden.
PS C:\Users\xxxx\AppData\Local\wsltty\bin> wsl -d centos7
[root@RP-T14 bin]# logout
PS C:\Users\xxxx\AppData\Local\wsltty\bin> .\wslbridge2.exe -d centos7
[root@RP-T14 bin]# exit
PS C:\Users\xxxx\AppData\Local\wsltty\bin>
```

So first I do a wsl shutdown.
Then wslbridge2.exe does not work.
Then I start  (a v2) distribution with wsl -d
And immediately after that, wslbridge2.exe also works as you can see.
When I do a wsl --shutdown, wslbridge2 is not working again.

So it does only work, when I use the "wsl -d" command in advance.
Its not only the centos7, all other distributions are also not working:

```
PS C:\Users\xxxx\AppData\Local\wsltty\bin> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu2004v1           Stopped         1
  Rocky8                 Stopped         2
  Fedora                 Stopped         2
  docker-desktop-data    Stopped         2
  docker-desktop         Stopped         2
  CentOS7                Stopped         2
  Rocky8docker           Stopped         2
  Rocky8dockerL          Stopped         2
PS C:\Users\xxxx\AppData\Local\wsltty\bin> wsl --shutdown
PS C:\Users\xxxx\AppData\Local\wsltty\bin> .\wslbridge2.exe -d Fedora
ERROR: GetVmId:271: CreateLxProcess: Das System kann die angegebene Datei nicht finden.

PS C:\Users\xxxx\AppData\Local\wsltty\bin> .\wslbridge2.exe -d Rocky8
ERROR: GetVmId:271: CreateLxProcess: Das System kann die angegebene Datei nicht finden.

PS C:\Users\xxxx\AppData\Local\wsltty\bin> .\wslbridge2.exe -d Rocky8docker
ERROR: GetVmId:271: CreateLxProcess: Das System kann die angegebene Datei nicht finden.
```

**Comment by Biswa96** [comment]
OK, understood the issue. The `wsl.exe -l -v` output explains it. I shall let you know about the fix.

**Comment by Biswa96** [comment]
I have added a fix in repository. Please test the wslbridge2.exe executable from here https://ci.appveyor.com/project/Biswa96/wslbridge2/builds/45822953/job/9q3kbgjbrlkuoflq/artifacts. Rename the existing wslbridge2.exe to something else. Then extract the executable from that link and place it in same path.

I missed the fact that one can use WSL1 with WSL from MS Store aka. lifted WSL. In your case, Ubuntu2004v1 is in WSL1 and it is set as default (see the star in front of it). If any WSL2 distro was set as default the issue would not happen.

**Comment by rola25** [comment]
Yes it works now! Thank you very much + Happy New Year 2023 ;-)
