### ISSUE TITLE
Error code: Wsl/Service/CreateInstance/MountVhd/0x80070020

### ISSUE THREAD

**Issue by mikelue** [Biswa96/wslbridge2#40]
The problem comes from WSL, see [microsoft/WSL issue-8696](https://github.com/microsoft/WSL/issues/8696#issuecomment-1471395475)

----
I'm facing the problem of wslbridg2 after run `wsl --update --web-download`, here is my error message:

command:
```sh
wsl --terminate Ubuntu
mintty --WSL= -h error
```

Error message:
```
/bin/wslbridge2: Exit 1.
note: wsl.exe output: 無法將磁片'C:\VMs\WSL-Ubuntu\ext4.vhdx'連結到 WSL2： The process cannot access the file because it is being used by another process.
Error code: Wsl/Service/CreateInstance/MountVhd/0x80070020
```

Sorry for the mandarin of error message.
Any comment would be appreciated.

My WSL version:
```
WSL version： 1.1.3.0
Core version： 5.15.90.1
WSLg version： 1.0.49
MSRDC version： 1.2.3770
Direct3D version： 1.608.2-61064218
DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version： 10.0.22621.1413
```

My Windows version:
```
Windows 11 Professional
22H2
OS Built	22621.1413
Windows Feature Experience Pack 1000.22639.1000.0
```

**Comment by Biswa96** [comment]
The error is coming from WSL, wslbridge2 is not related. You may get same error after running wsl.exe.

**Comment by mikelue** [comment]
> The error is coming from WSL, wslbridge2 is not related. You may get same error after running wsl.exe.

Yes I did. I will reply this issue to WSL. Thanks a lot. 😁
