### ISSUE TITLE
WSL2 with mirrored networking mode error ioctl(SIOCGIFADDR): Address not available

### ISSUE THREAD

**Issue by irakhlin** [Biswa96/wslbridge2#41]
Hello,

I am using the most updated version of wslbridge2.exe:
```bash
$ %ConEmuBaseDirShort%\wsl\wslbridge2.exe --help

wslbridge2 v0.12 : Runs a program within a Windows Subsystem for Linux (WSL) pty.
Copyright (C) 2019-2022 Biswapriyo Nath.
Licensed under GNU General Public License version 3 or later.
```

I have enabled the new [experimental mirrored networking mode](https://devblogs.microsoft.com/commandline/windows-subsystem-for-linux-september-2023-update/) in WSL2. 

On launching a session as I normally do in conemu, I get the following message/warning:
ioctl(SIOCGIFADDR): Address not available

The shell session seems to continue to function normally without any other issues, that I can identify. But am more than happy to troubleshoot. I am not too familiar with the code base here to identify what socket this is referencing, I am assuming this is trying to connect to address of the wsl2 network stack which would no longer exist and seemingly should connect to localhost. I had what I assume is a simillar issue with Pycharm/Intellij using this configuration and they had resolved the issue [here](https://youtrack.jetbrains.com/issue/IDEA-332852/Support-WSL-2.0-mirrored-network#focus=Comments-27-8325165.0-0) by allowing the proxy to connect to localhost. 

Some additional debugging output:
```bash
$ wslinfo --networking-mode
mirrored

$ wsl --version
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2861
```

edit: Looking at the error and code, it would seem the issue is potentially coming from this call: https://github.com/Biswa96/wslbridge2/blob/1770edd37f6f6c767970dcec69896ef22fe4618c/src/nix-sock.c#L176C1-L176C1

It seems this function is using the eth0 interface, on my machine (a laptop with multiple network interfaces) wsl2 is not using eth0:
```bash
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether {removed mac} brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether {removed mac} brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.160/24 brd 10.0.0.255 scope global noprefixroute eth1
       valid_lft forever preferred_lft forever
    inet6 {removed}/64 scope global nodad deprecated noprefixroute
       valid_lft forever preferred_lft 0sec
    inet6 {removed}/128 scope global nodad noprefixroute
       valid_lft forever preferred_lft forever
    inet6 {removed}/64 scope link nodad noprefixroute
       valid_lft forever preferred_lft forever
4: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether {removed mac} brd ff:ff:ff:ff:ff:ff
5: loopback0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether {removed mac} brd ff:ff:ff:ff:ff:ff
    .... abbreviated ....
```

I guess the question comes down to, how is this used? It seems in setting the env vars, does it break without it? If so could a call to [getifaddrs](https://man7.org/linux/man-pages/man3/getifaddrs.3.html) be made to get back a list of the available interfaces and maybe choose the first one with an active ip?

**Comment by irakhlin** [comment]
@Biswa96  maybe this will help  but it seems I may have solved the issue, I am more than happy to push up a PR, my changes are on my branch here: https://github.com/Biswa96/wslbridge2/compare/master...irakhlin:wslbridge2:add_mirrored_networking_support?expand=1

It would seem that you probably default to eth0 as the network interface because without mirrored networking mode wsl would only get its own single independent network interface so it was safe to assume eth0 would work. With mirrored networking mode enabled all your machines interfaces will actually be accessible from wsl, for example,
```bash
ip a 
```
returns lo, loopback0 along with eth0.... eth6.. all the various network interfaces configured in windows.

I added a function to identify if wsl2 mirrored networking mode was enabled, with a fallback to it NOT being enabled. Using what seem like the [officially suggested method](https://github.com/dorssel/usbipd-win/issues/714#issuecomment-1749077360) that was later implemented in that [project](https://github.com/dorssel/usbipd-win/blob/2d82098e87a0eb351063e94fb25a127d2888f1a0/Usbipd/Wsl.cs#L328). 

If mirrored mode is not detected, code should fallback to the existing logic, otherwise logic should be as followed:
- Get the number of network interfaces with an initialized IP address
- Iterate though those network interfaces, and get the first one that is not a localhost address (127.0.0.1) to ignore interface lo
- set both WSL_GUEST_IP and WSL_HOST_IP to the IP of that network interface.

With the changes on my branch and a rebuild of wslbridge2-backend, on startup I am not getting the following as expected:
```bash
$ echo $WSL_GUEST_IP
10.0.0.160

$ echo $WSL_HOST_IP
10.0.0.160

$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether {mac_removed} brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether {mac_removed} brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.160/24 brd 10.0.0.255 scope global noprefixroute eth1
       valid_lft forever preferred_lft forever
..remained output not shown..
```

I am a bit rusty on my C so suggestions or changes I am more than happy to make if it helps this get merged in but for now its working for me.

**Comment by Biswa96** [comment]
The changes look good to me at first glance. Please let me investigate the issue first. I shall let you know.

**Comment by Biswa96** [comment]
I chose to remove the `WSL_HOST_IP` and `WSL_GUEST_IP` environment variables. It was added for experiments when there was no official documentation to get the IP addresses. 

I appreciate your effort for investigating this issue. I did not know about the feature and other related topics.
