### ISSUE TITLE
Can wslbridge2 return ws_xpixel and ws_ypixel?

### ISSUE THREAD

**Issue by mikoto2000** [Biswa96/wslbridge2#44]
The following sections set zero, but some terminals should be able to retrieve pixel-level size.

https://github.com/Biswa96/wslbridge2/blob/5f444e639cc5ff6eff8945094ee68d0583adaafe/src/wslbridge2-backend.cpp#L275-L276

https://github.com/Biswa96/wslbridge2/blob/5f444e639cc5ff6eff8945094ee68d0583adaafe/src/wslbridge2-backend.cpp#L301-L303

Is it possible to set these ws_xpixel and ws_ypixel and return them to the app?

**Comment by Biswa96** [comment]
I am not sure. @mintty may help with terminal related topics.

**Comment by mintty** [comment]
Mintty provides these values when sending SIGWINCH. I think wslbridge could propagate them along with the cell size, where handling struct winsize. I may find some time occasionally to check but it's a change in wslbridge.

**Comment by mikoto2000** [comment]
We are setting the value of winp with recv, but can you achieve this by simply deleting the line that overwrites it with zero?

**Comment by Biswa96** [comment]
Fixed in above PR.

**Comment by mintty** [comment]
Thanks for taking this patch. Can you make it a release please, for easier integration in wsltty?

**Comment by Biswa96** [comment]
Released v0.13.

**Comment by mintty** [comment]
Sorry I didn't test before asking for a release.
But unfortunately, this patch (and thus also 0.13) makes wslbridge2 fail on my systems.
I don't see why this small change would break the backend; maybe a corresponding change in the frontend would also be needed?

**Comment by mikoto2000** [comment]
@mintty 
What exactly does it mean when it breaks?

I rebuilt and run it on Cygwin.(`./wslbridge2 --login`)

It works, but it seems to be in a state where the prompt is not displayed until several Enter keys are pressed after wslbridge2 starts.

Also, strangely, when I built and ran wslbridge2 v0.12, it terminated with an `ERROR: GetVmId:312: CreateLxProcess: NULL 参照ポインターがスタブに渡されました。` error. Maybe my environment is bad.

**Comment by mintty** [comment]
WSL V1: it hangs, blank terminal window
WSL V2: it terminates, window closes
