### ISSUE TITLE
hvpty login option

### ISSUE THREAD

**Issue by mintty** [Biswa96/wslbridge2#6]
wslbridge supports starting the WSL shell as a login shell,
triggered by checking its own `argv[0][0] == '-'`
Although WSL distros do not seem to make much difference on login shell, this would be a good option to have in general.

**Comment by Biswa96** [comment]
Added the login option. Can you check?

**Comment by mintty** [comment]
./hvpty -d Ubuntu
/bin/dash: 0: Illegal option --

It seems you add `--login` to the WSL bash, but it should just be `-l` to work with all shells.

./hvpty -d Debian
.profile

It seems login mode is enabled even without hvpty `-l` option.
Same with wslbridge2.

**Comment by Biswa96** [comment]
Can you try this patch [test.patch.txt](https://github.com/Biswa96/wslbridge2/files/3586797/test.patch.txt)? BTW, rprichard's wslbridge also has that code.

**Comment by mintty** [comment]
Works fine, thank you.
