### ISSUE TITLE
hvpty options

### ISSUE THREAD

**Issue by mintty** [Biswa96/wslbridge2#7]
hvpty does not have options `-t` (maybe not needed) and `-e` (useful).
Option `-C~` stalls hvpty. Even parallel instances cannot be started while hvpty is running (and stalled) with this option.
Sometimes it's reporting
`assertion "ret == 0" failed: file "hvpty.cpp", line 58, function: SOCKET Initialize(std::wstring&, GUID*)`
(not sure yet whether this is always related to an instance with `-C~`).

**Comment by Biswa96** [comment]
hvpty uses real pty feature of Linux kernel. Hence the `-T` or `-t` option is not required. Can you provide a real case scenario of `-e` option so that I can test it.

Also `-C` is replaced with `windir` and `wsldir` options.

**Comment by mintty** [comment]
Currently, mintty uses `-e` to make `APPDATA` available to the WSL session, where mintty resources like themes are stored, so they can be managed e.g. with the `mintheme` tool.

**Comment by dxhisboy** [comment]
@mintty Actually I let mintty find their themes with -C option, also, passing envvar to WSL can be done by a WSLENV variable as m$ suggested.

**Comment by mintty** [comment]
I don't see WSLENV documented; also, I think hvpty and wslbridge2, basically serving the same purpose, should have compatible arguments, in order to avoid too much fiddling around (e.g. inside mintty).

**Comment by Biswa96** [comment]
Added environment option. Can you check?

**Comment by mintty** [comment]
Works fine, thank you.

**Comment by Biswa96** [comment]
Would it be a big difference for mintty if I remove the pipe related things i.e. the `-t` and `-T` options from wslbirdge2? After all it always use pty mode.

**Comment by mintty** [comment]
No, I've removed -t from mintty.
