### ISSUE TITLE
hvpty does not compile in cygwin-32

### ISSUE THREAD

**Issue by mintty** [Biswa96/wslbridge2#8]
After removing the -m64 from Makefiles, still the GetVmId module won't compile, due to some embedded assembler instructions. Where is that module from and does a 32-bit version exist?

**Comment by Biswa96** [comment]
Is it necessary to compile for 32bit? I mean WSL isn't available for 32bit Windows.

To use it's C counterpart, it needs latest Windows headers (winternl.h) to be available in cygwin repositories. Or I have to do some pointer black magic.

**Comment by mintty** [comment]
It's not necessary for wsltty. But mintty, run in Cygwin-32, can be invoked explicitly with option `--WSL` or from the session launcher menu. This would not work with WSL 2 then.

**Comment by Biswa96** [comment]
Removed the inline assembly. I don't know if that works in 32 bit cygwin because there may be something depends on 64 bit specific things. The `GetVmId.cpp` is not required if there will be a proper API to get VM ID (https://github.com/microsoft/WSL/issues/4131).

**Comment by Biswa96** [comment]
Removed the inline assembly. I don't know if that works in 32 bit cygwin because there may be something depends on 64 bit specific things. The `GetVmId.cpp` is not required if there is a proper API to get VM ID (https://github.com/microsoft/WSL/issues/4131).

**Comment by mintty** [comment]
Thanks, however, it doesn't work anyway:
error: 'C:\WINDOWS\System32\wsl.exe' does not exist
Somehow, this would work with previous bash.exe...

**Comment by Biswa96** [comment]
Try now.

**Comment by mintty** [comment]
It compiles, but gives me a segmentation fault.

**Comment by Biswa96** [comment]
Apology for late reply. I was setting up Cygwin x86 environment. The issue was with my old nemesis [calling conventions in vtable](https://stackoverflow.com/q/52457407/8928481).

**Comment by Biswa96** [comment]
Did it work now?

**Comment by Biswa96** [comment]
Any reply?

**Comment by Biswa96** [comment]
@mintty intty Any reply?

**Comment by mintty** [comment]
Yes it works, thank you.
However, there are a few warnings. The attached patch fixes them, and also the backend compile failure on Alpine.
[compile.patch.txt](https://github.com/Biswa96/wslbridge2/files/3602285/compile.patch.txt)

**Comment by Biswa96** [comment]
Those will be fixed in upcoming commits....
