### ISSUE TITLE
hvpty command argument

### ISSUE THREAD

**Issue by mintty** [Biswa96/wslbridge2#9]
wslbridge2, like wslbridge, also takes a command argument which would be used instead of starting a shell, like `wslbridge2 ls` or `wslbridge2 ls -l`.
This does not work with hvpty.

**Comment by Biswa96** [comment]
For hvpty, I thought to use that feature but it opens up shell everytime, then run the command and exit. This isn't efficient to do a small work.

Whereas the WSL init ELF binary uses [splice(2)][1] which uses less CPU work. I have to use some pipes in hvpty-backend. This takes some time to implement...


[1]: http://man7.org/linux/man-pages/man2/splice.2.html

**Comment by Biswa96** [comment]
Working on this...

**Comment by mintty** [comment]
Don't understand...
Wouldn't you simply execvp the given argument instead of shell, just like in wslbridge2?

**Comment by Biswa96** [comment]
I was doing this with `/bin/sh -c` style string? Will it be right to assume that `-c` option is available for every shell to run command?

**Comment by mintty** [comment]
You should not use sh -c for this purpose; this would make trouble with quoting (or rather not quoting) special characters and spaces in arguments. Also it needs to run a shell in the first place which is not necessary.
Simply put the requested command and parameters into the args array for exec. This can be monitored in wslbridge2:
```
+        for (unsigned int i = 0; i < params.argv.size(); i++)
+          printf("%d <%s>\n", i, params.argv[i]);
         execvp(params.prog.c_str(), params.argv.data());

**Comment by Biswa96** [comment]
@mintty Now try.

**Comment by mintty** [comment]
Works fine, thank you.
